[PR] PR Sync후 클릭된 데이터 전달 로직 구현
boostcampwm-2022/android10-PlzStop pull request #39
Opened 2022-11-18 14:33 UTC by koreatlwls

## PR Description
- 관련 이슈 : 
- 관련 문서 : 

## Changes
- PR Sync후 클릭된 데이터 전달 로직 구현

2022-11-18 16:47 UTC, DoTheBestMayB requested changes
새벽까지 열심히 하시네요, 수고하셨습니다👍

@jeeminimini
앱 실행 후 검색 창과 홈 화면을 뒤로가기로 여러 번 반복 하다보면 아래와 같은 에러가 발생합니다.
다음 작업 이어서 하시는 분이 아래 에러를 수정할 수 있도록 관련 정보 코멘트로 남겨주시면 좋을 것 같아요!


> E/TileStreaming: error=8 layer=108 tile=15/27943/12692
> E/TileStreaming: error=8 layer=108 tile=15/27944/12692
> E/TileStreaming: error=8 layer=108 tile=15/27943/12693
> E/TileStreaming: error=8 layer=108 tile=15/27944/12693
> E/TMapGpsManager: onLocationChange : Location[gps 37.539900,127.070998 hAcc=5.0 et=+19314d16h4m35s918ms alt=0.0 vAcc=0.5 vel=0.0 sAcc=0.5 bear=0.0 bAcc=30.0 {Bundle[mParcelledData.dataSize=96]}]
> D/EGL_emulation: app_time_stats: avg=32.72ms min=4.01ms max=62.52ms count=31
> E/TMapGpsManager: onLocationChange : Location[network 37.422094,-122.083922 hAcc=600.0 et=+17h15m2s459ms {Bundle[mParcelledData.dataSize=68]}]
> E/TMapGpsManager: onLocationChange : Location[network 37.422094,-122.083922 hAcc=600.0 et=+17h15m2s459ms {Bundle[mParcelledData.dataSize=68]}]
> E/TMapGpsManager: onLocationChange : Location[network 37.422094,-122.083922 hAcc=600.0 et=+17h15m2s459ms {Bundle[mParcelledData.dataSize=68]}]
> D/AndroidRuntime: Shutting down VM
> D/EGL_emulation: app_time_stats: avg=512.13ms min=5.47ms max=12481.30ms count=26
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.stop, PID: 2650
>     java.lang.IllegalStateException: Fragment MapFragment{b89f9d0} (00071cce-e6c0-4859-8e7e-3d00f035ca92) not attached to a context.
>         at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
>         at com.stop.ui.map.MapFragment.onLocationChangeListener$lambda$16(MapFragment.kt:231)
>         at com.stop.ui.map.MapFragment.$r8$lambda$w7SAFdPdBz87M4Yi760Gf-XrcRQ(Unknown Source:0)
>         at com.stop.ui.map.MapFragment$$ExternalSyntheticLambda8.onLocationChange(Unknown Source:2)
>         at com.skt.tmap.TMapGpsManager$1.onLocationChanged(TMapGpsManager.java:65)
>         at android.location.LocationListener.onLocationChanged(LocationListener.java:63)
>         at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3180)
>         at android.location.LocationManager$LocationListenerTransport$1.operate(LocationManager.java:3177)
>         at com.android.internal.listeners.ListenerExecutor.lambda$executeSafely$0(ListenerExecutor.java:127)
>         at com.android.internal.listeners.ListenerExecutor$$ExternalSyntheticLambda0.run(Unknown Source:8)
>         at android.os.Handler.handleCallback(Handler.java:938)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loopOnce(Looper.java:201)
>         at android.os.Looper.loop(Looper.java:288)
>         at android.app.ActivityThread.main(ActivityThread.java:7842)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

2022-11-18 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/model/nearplace/Place.kt
>  }
API를 통해 받아 온 데이터 모델인 Poi를 Repository에 전달할 때 data 모듈의 Place로 변환하고,
이 Place를 domain 모듈에 전달할 때 domain 모듈의 Place로 변환하고 있네요.

Repository에 전달 할 때 Poi로 바로 전달하지 않고 변환하신 이유가 있으신가요?

2022-11-18 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
> +    ): Flow<List<Place>> = flow<List<Place>> {
```suggestion
    ): Flow<List<Place>> = flow {
```
IDE 힌트에서 fow 변수의 타입 `<List<Place>>`를 명시하지 않아도 된다고 나오네요!

2022-11-18 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
> +        emit(
❓질문❓

> Collects the value emitted by the upstream. This method is not thread-safe and should not be invoked concurrently.

flow의 emit 함수에 대해 IDE에서 쓰레드에 안전하지 않기 때문에 동시에 호출하면 안 된다고 적혀 있습니다.

동시에 호출하면 안 된다는 것은, 특정 flow 객체 1개에 대해 emit 함수를 동시에 호출하면 안 된다는 건가요?
혹은 emit 함수 파라미터로 전달되는 value가 동일한, flow를 2개 이상 만들면 안 된다는 건가요?

emit 함수 파라미터로 전달되는 value가 동일한, flow를 2개 이상 만들면 안 된다면 RepositoryModule 클래스에서 NearPlaceRepositoryImpl를 Singleton으로 주입하면 안 되는 걸까요?

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/build.gradle
> +    id 'kotlin-parcelize'
Serializable 대신 Parcelable을 사용하려는 시도 좋습니다👍

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/model/Event.kt
> +open class Event<out T>(private val content : T){
```suggestion
class Event<out T>(private val content : T){
```
화면 회전에 따른 LiveData 핸들링 좋습니다👍
Event 클래스를 상속하는 클래스가 없기 때문에 open 접근자는 지워주는 것이 좋을 것 같습니다!

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/model/Event.kt
> +    }
Event 클래스에서 IDE 자동 정렬을 한 번 해주면 좋을 것 같아요

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +        }
개발 과정에서만 출력이 보이도록 Log 대신 Timber를 사용하는 것이 좋습니다!
Kotlin convention이 적용되지 않았는데, 커밋 하기 전에 IDE 자동 정렬 기능을 한 번 실행 후 커밋하시면 좋을 것 같아요!

지도 부분은 지민 님 혹은 경현 님이 구현하신 것 같아서 멘션 드립니다!
@jeeminimini @khcho226

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>          private const val ROAD_ADDRESS_TYPE = "A04"
@jeeminimini @khcho226 
T MAP에서 사용하는 ADDRESS_TYPE이 정의 되어 있다면, Enum class를 활용해보는 것은 어떨까요?

2022-11-18 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchViewModel.kt
> +    var currentLocation = Location(0.0, 0.0)
location을 (0.0, 0.0)으로 미리 할당 해뒀을 때 발생하는 문제는 없을까요?🤔

2022-11-20 03:13 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +        }
이 부분 제가 구현했었지만, 시진님이 수정하신 부분입니다!

2022-11-20 03:13 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +        }
try catch로 예외처리 👍

2022-11-20 03:13 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>          private const val ROAD_ADDRESS_TYPE = "A04"
아 enum 미쳐생각하지 못했네요! 감사합니다

2022-11-20 03:13 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>          tMapView.setOnEnableScrollWithZoomLevelListener { _, _ ->
`setOnEnableScrollWithZoomLevelListener`가 clickMap()함수에도 존재해서 여기에서 지우고 clickMap()의 Enable에 `isTracking = false` 을 두면 될 것 같습니다!

2022-11-20 03:13 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/nearplace/PlaceSearchViewModel.kt
> +    var currentLocation = Location(0.0, 0.0)
MapFragment에서 TMapGpsManager.OnLocationChangedListener로 currentLocation을 갱신하고 있습니다!

2022-11-20 03:27 UTC, jeeminimini approved these changes
수고하셨습니다!

2022-11-20 08:17 UTC, koreatlwls commented on data/src/main/java/com/stop/data/model/nearplace/Place.kt
>  }
datasource의 모델을 repository 전용 모델로 변경하고 domain 모델전용 모델로 변경 하였습니다

2022-11-20 08:19 UTC, koreatlwls commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +        }
테스트한다고 저렇게 되어있고 다음PR에서 삭제되어있습니다

2022-11-20 08:19 UTC, koreatlwls commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>          private const val ROAD_ADDRESS_TYPE = "A04"
지민님이 추후 작업하시는걸로 알고 확인하겠습니다 !

2022-11-20 08:20 UTC, koreatlwls commented on data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
> +    ): Flow<List<Place>> = flow<List<Place>> {
0c4a797c7eee500921191d918d2b27f425450ec6

2022-11-20 08:21 UTC, koreatlwls commented on data/src/main/java/com/stop/data/repository/NearPlaceRepositoryImpl.kt
> +        emit(
사무실에서 이야기 나누면좋을꺼같아요 해당 내용은!!

2022-11-20 08:21 UTC, koreatlwls commented on presentation/src/main/java/com/stop/model/Event.kt
> +open class Event<out T>(private val content : T){
0c4a797c7eee500921191d918d2b27f425450ec6

2022-11-20 08:21 UTC, koreatlwls commented on presentation/src/main/java/com/stop/model/Event.kt
> +    }
0c4a797c7eee500921191d918d2b27f425450ec6

2022-11-20 08:29 UTC, merged