[PR] map의 공통 로직 TMap class 구현 및 버스 실시간 bus line 그리기
boostcampwm-2022/android10-PlzStop pull request #50
Opened 2022-11-24 11:12 UTC by jeeminimini

## PR Description
- 관련 이슈 : 
- 관련 문서 : 

## Changes
- 미션과 지도 화면에서 쓰이는 TMap의 공통적인 부분을 TMap class로 구현
- TMap class를 상속받는 MissionTMap과 MapTMap을 구현, 콜백을 이용해서 연결함 -> fragment 코드 줄임
- 임의의 버스를 5초 간격으로 받아와 실시간으로 line 그리기 구현
 
## Screenshots
<img src="https://user-images.githubusercontent.com/74500793/203769993-6c41e77d-3710-4ee3-976d-47dea0f54e8a.jpg" width="250" height="500"/>

2022-11-24 16:47 UTC, DoTheBestMayB requested changes

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/network/WsBusApiService.kt
> +    ): NetworkResult<GetBusNowLocationResponse>
```suggestion
    @GET(GET_BUS_NOW_LOCATION_URL)
    suspend fun getBusNowLocation(
        @Query("busRouteId") busRouteId: String,
        @Query("resultType") resultType: String = JSON
    ): NetworkResult<GetBusNowLocationResponse>
```

NetworkModule에서 CustomInterceptor가 baseUrl에 따라 serviceKey를 넣어주고 있기 때문에
serviceKey 파라미터는 지우셔도 됩니다🙂

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/network/WsBusApiService.kt
> +        private const val JSON = "json"
문자열, 상수 const로 빼는 습관 👍
제가 다른 API 작성할 때, 빼주지 않았네요😅

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/model/nowlocation/BusBody.kt
> +data class BusBody(
`@JsonClass(generateAdapter = true)`를 붙이는 것이 필수가 아니군요.. moshi에 대한 학습이 부족했습니다.

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/model/nowlocation/BusInfo.kt
> +    )
```suggestion
    fun toRepositoryModel() = BusInfoRepositoryItem(
        isArrivedAtStation = isArrivedAtStation,
        sectionId = sectionId,
        latitude = latitude,
        longitude = longitude,
        busId = busId,
        busNumber = busNumber,
        isRun = isRun,
    )
```

데이터 클래스의 파라미터가 많을 때, 파라미터 이름을 적어주면 가독성이 좋아지고
파라미터가 추가되었을 때, 작업하기도 편리합니다.

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/model/nowlocation/GetBusNowLocationResponse.kt
> +data class GetBusNowLocationResponse(
여기서는 다시 `@JsonClass(generateAdapter = true)`를 붙여 주셨네요.

어떤 차이가 있을까요?🤔

2022-11-24 16:47 UTC, DoTheBestMayB commented on data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSourceImpl.kt
> +                is NetworkResult.Success -> this.data.busBody.busInfo.first().toRepositoryModel()
지도에 버스를 표시하기 위한 테스트적인 관점에서 노선에 있는 버스 목록 중 첫 번째 버스를 선택하기 위해 `first()` 코드를 사용하신 것 같습니다.

지금은 이러한 사실을 알고 계시겠지만, 나중에 작업을 다시 이어갈 때 내가 생각하는 결과물을 보여주지 않으면 이 부분 때문에 그렇다는 사실을 알아차리기란 쉽지 않습니다.

RemoteDataSource는 노선에 대한 모든 버스 정보를 제공하고, 사용하는 usecase에서 선택하도록 하는 것은 어떨까요?

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapTMap.kt
> +class MapTMap(
MapTMap... 어감이 어색합니다

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +                PERSON_MARKER_IMG,
상수화의 습관화 아주 좋습니다👍

하지만 안드로이드 의존성이 있는 R.Xxx.Xxx를 통해 얻은 숫자를 companion object에 둬도 괜찮을까요🤔(진짜 모름)

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +    }
xor 연산자를 이용해서 코드를 줄여볼까요?

```kotlin
val VISIBLE = 8
var visibility = 0

visibility = visibility.xor(VISIBLE) // visibility는 몇이 될까요?
visibility = visibility.xor(VISIBLE) // visibility는 몇이 될까요?
```

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>                  R.drawable.ic_baseline_stars_32,
여기서는 `R.drawable.ic_baseline_stars_32`을 바로 사용하고 있네요🤔

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapHandler.kt
> +    fun setOnLocationChangeListener(location: android.location.Location)
`import android.location.Location`를 상단에 넣어줄까요?

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
> +        }
tracking이 멈추는 대신, 버스의 위치를 Tracking 하는 것은 어떤가요?

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
> +        private val INIT_LOCATION = Location(0.0, 0.0)
0.0, 0.0... 괜찮을까요?

![image](https://user-images.githubusercontent.com/48354989/203833411-4b1acc01-3064-43b9-aa74-8c53bac8b0f4.png)

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/util/Handler.kt
> +}
얘는 어떤 역할을 하나요?

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/util/TMap.kt
> +    lateinit var initLocation: Location
lateinit var 사이에 끼어있는 var... 😅

2022-11-24 16:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/util/TMap.kt
> +    private fun checkKoreaLocation(location: android.location.Location): Boolean {
이미 내부 라이브러리에서 사용하고 있는 변수 명과 겹치면 이런 단점이 있네요

2022-11-27 04:16 UTC, koreatlwls commented on data/src/main/java/com/stop/data/remote/model/nowlocation/GetBusNowLocationResponse.kt
> +data class GetBusNowLocationResponse(
해당 annotation으로 codegen방식으로 직렬화 역직렬화 하는 과정을 거쳐요!
gson은 reflection방식으로 직렬화 역직렬화하고
moshi는 해당 annotation 붙이면 codegent 방식으로해요
코드리뷰남기다가 보고 남깁니다!

https://www.infoworld.com/article/2075801/reflection-vs--code-generation.html

2022-11-27 04:16 UTC, koreatlwls commented on presentation/src/main/res/values/strings.xml
> +    <string name="mission_close_image_view_description">미션 종료 버튼입니다.</string>
%1$s:%2$s 이런식으로 작성하는게 좋아요 !! 
그 언어에 따라 순서가 바뀔때 순서가 바뀔수도 있데요 그래서 순서를 명시하는 1 2 3 붙여주는게 좋다고합니다

2022-11-27 07:43 UTC, jeeminimini commented on data/src/main/java/com/stop/data/remote/model/nowlocation/BusBody.kt
> +data class BusBody(
붙이는게 맞는 것 같습니다...!
https://stackoverflow.com/questions/58501918/whats-the-use-of-moshis-kotlin-codegen

2022-11-27 07:48 UTC, jeeminimini commented on data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSourceImpl.kt
> +                is NetworkResult.Success -> this.data.busBody.busInfo.first().toRepositoryModel()
넵 그렇게 수정하겠습니다!

2022-11-27 07:48 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapTMap.kt
> +class MapTMap(
저도.. 짜면서 구리다 생각했지만.. 딱히 떠오르지 않았습니다..
혹시 추천해주실 수 있나요?? 👀

2022-11-27 07:55 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +                PERSON_MARKER_IMG,
어... 저도 잘 모르겠습니다,,,, 안되려나요..?

2022-11-27 07:56 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +    }
오 훨씬 깔끔하네요! 고치겠습니다

2022-11-27 07:57 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>                  R.drawable.ic_baseline_stars_32,
이건 따로 정의하는 걸 까먹었습니다...

2022-11-27 07:57 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapHandler.kt
> +    fun setOnLocationChangeListener(location: android.location.Location)
아래 말씀하신 것 처럼 Location이라는 data class를 만들어줘서 저렇게 하였습니다!

2022-11-27 07:58 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
> +        }
이부분 시진님과 얘기해봤을 때 굳이 버스 Tracking까지 필요없을 것 같다고 하셨는데,
다같이 얘기해보면 좋을 것 같네요!

2022-11-27 08:00 UTC, jeeminimini commented on presentation/src/main/res/values/strings.xml
> +    <string name="mission_close_image_view_description">미션 종료 버튼입니다.</string>
아~~ 몰랐던 사실이네요! 감사합니다

2022-11-27 08:01 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/mission/MissionFragment.kt
> +        private val INIT_LOCATION = Location(0.0, 0.0)
다른 곳에서 바로 갱신해서 상관없을 것이라 생각했습니다...!
만일 초기 위치가 정해지면 그곳으로 하는게 좋겠네요!

2022-11-27 08:02 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/util/Handler.kt
> +}
Handler가 Map과 Mission에 따라 달라지기 때문에 그들을 하나로 묶어주기 위한 상위 interface입니다.

2022-11-27 08:03 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/util/TMap.kt
> +    lateinit var initLocation: Location
이쁘게 고치겠습니다.....

2022-11-27 08:46 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
> +    }
https://github.com/boostcampwm-2022/android10-PlzStop/pull/50/commits/2d176bd00dae38f9024af86149840f959df9d525

2022-11-27 08:47 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/map/MapFragment.kt
>                  R.drawable.ic_baseline_stars_32,
https://github.com/boostcampwm-2022/android10-PlzStop/pull/50/commits/87c0d51b66d94a3a81171983b5599501878824a0

2022-11-27 08:47 UTC, DoTheBestMayB commented on presentation/src/main/java/com/stop/ui/map/MapTMap.kt
> +class MapTMap(
1. TMap 클래스를 사용하는 대신, MapFragment에서 사용할 함수만 추가해둔 MapTMap 객체를 만들어야 할까요?
2. TMapForMapFargment라고 이름을 지을 수 있을 것 같아요.

2022-11-27 08:47 UTC, jeeminimini commented on presentation/src/main/java/com/stop/ui/util/TMap.kt
> +    lateinit var initLocation: Location
https://github.com/boostcampwm-2022/android10-PlzStop/pull/50/commits/25fe1623fec22419dd3d4babe1a7cc3dcc677824

2022-11-27 08:48 UTC, jeeminimini commented on presentation/src/main/res/values/strings.xml
> +    <string name="mission_close_image_view_description">미션 종료 버튼입니다.</string>
https://github.com/boostcampwm-2022/android10-PlzStop/pull/50/commits/f0d8b393f9c92c364a3be03c8dcd6722465b7d0c

2022-11-27 08:53 UTC, jeeminimini commented on data/src/main/java/com/stop/data/remote/source/nowlocation/NowLocationRemoteDataSourceImpl.kt
> +                is NetworkResult.Success -> this.data.busBody.busInfo.first().toRepositoryModel()
https://github.com/boostcampwm-2022/android10-PlzStop/pull/50/commits/a4058c7d287cb2fef75970b774c711d462ad20f3

2022-11-27 13:10 UTC, DoTheBestMayB approved these changes

2022-11-27 13:11 UTC, koreatlwls approved these changes
수고하셨습니다.

2022-11-27 13:27 UTC, merged